name: Android CI Build

on: 
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Android CI Build"
      - name: checkout
        uses: actions/checkout@v2