name: Android PR Build Check

on: 
  pull_request:
    branches:
      - 'develop'
    paths:
      - '***.kt'
      - '***.xml'
      - '***.gradle'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Android CI Build"

      - name: checkout
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # そのまま実行すると./gradlew: Permission deniedが出るので権限を付与する
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Compile
        run: ./gradlew assembleDebug
